//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniKiosk.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmniKiosk.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Information.
        /// </summary>
        public static string AddressInformation {
            get {
                return ResourceManager.GetString("AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details.
        /// </summary>
        public static string BankDetails {
            get {
                return ResourceManager.GetString("BankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information.
        /// </summary>
        public static string BankInformation {
            get {
                return ResourceManager.GetString("BankInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank-level encryption.
        /// </summary>
        public static string BankLevel {
            get {
                return ResourceManager.GetString("BankLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Created Successfully!.
        /// </summary>
        public static string BeneficiaryCreatedSuccess {
            get {
                return ResourceManager.GetString("BeneficiaryCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Details.
        /// </summary>
        public static string BeneficiaryDetails {
            get {
                return ResourceManager.GetString("BeneficiaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Information.
        /// </summary>
        public static string BeneficiaryInformation {
            get {
                return ResourceManager.GetString("BeneficiaryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Receives.
        /// </summary>
        public static string BeneficiaryReceives {
            get {
                return ResourceManager.GetString("BeneficiaryReceives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your beneficiary profile has been saved.
        /// </summary>
        public static string BeneProfileSaved {
            get {
                return ResourceManager.GetString("BeneProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Rates.
        /// </summary>
        public static string BestRates {
            get {
                return ResourceManager.GetString("BestRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse our products and services.
        /// </summary>
        public static string BrowseTxt {
            get {
                return ResourceManager.GetString("BrowseTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BTxt {
            get {
                return ResourceManager.GetString("BTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Photo.
        /// </summary>
        public static string CapturePhoto {
            get {
                return ResourceManager.GetString("CapturePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a photo for verification purposes.
        /// </summary>
        public static string CapturePhotoDesc {
            get {
                return ResourceManager.GetString("CapturePhotoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the country where your recipient will receive money.
        /// </summary>
        public static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how you&apos;d like to complete this transaction.
        /// </summary>
        public static string ChoosePayment {
            get {
                return ResourceManager.GetString("ChoosePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitive pricing.
        /// </summary>
        public static string Competitive {
            get {
                return ResourceManager.GetString("Competitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete all required fields to create a new sender profile.
        /// </summary>
        public static string CompleteRequiredFields {
            get {
                return ResourceManager.GetString("CompleteRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete all required fields to create a new beneficiary profile.
        /// </summary>
        public static string CompleteRequiredFieldsBene {
            get {
                return ResourceManager.GetString("CompleteRequiredFieldsBene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Exit.
        /// </summary>
        public static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Beneficiary.
        /// </summary>
        public static string CreateNewBeneficiary {
            get {
                return ResourceManager.GetString("CreateNewBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new beneficiary to continue.
        /// </summary>
        public static string CreateToContinue {
            get {
                return ResourceManager.GetString("CreateToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method.
        /// </summary>
        public static string DeliveryMethod {
            get {
                return ResourceManager.GetString("DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive the OTP?.
        /// </summary>
        public static string DidntReceiveOTP {
            get {
                return ResourceManager.GetString("DidntReceiveOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Beneficiary Details.
        /// </summary>
        public static string EnterBeneficiaryDetails {
            get {
                return ResourceManager.GetString("EnterBeneficiaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your details to verify your identity.
        /// </summary>
        public static string EnterDetailsVerify {
            get {
                return ResourceManager.GetString("EnterDetailsVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 6-Digit OTP.
        /// </summary>
        public static string EnterOTP {
            get {
                return ResourceManager.GetString("EnterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the OTP to proceed with your transaction..
        /// </summary>
        public static string EnterOTPToProceed {
            get {
                return ResourceManager.GetString("EnterOTPToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Sender Details.
        /// </summary>
        public static string EnterSenderDetails {
            get {
                return ResourceManager.GetString("EnterSenderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?
        ///
        ///Your current transaction will be cancelled..
        /// </summary>
        public static string ExitConfirmMessage {
            get {
                return ResourceManager.GetString("ExitConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Processing.
        /// </summary>
        public static string FastProcessing {
            get {
                return ResourceManager.GetString("FastProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast, secure, and transparent international money transfers.
        /// </summary>
        public static string FastSecureTransfers {
            get {
                return ResourceManager.GetString("FastSecureTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields marked with * before saving.
        /// </summary>
        public static string FillAllRequiredFields {
            get {
                return ResourceManager.GetString("FillAllRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much would you like to send?.
        /// </summary>
        public static string HowMuch {
            get {
                return ResourceManager.GetString("HowMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC/Passport.
        /// </summary>
        public static string ICPassport {
            get {
                return ResourceManager.GetString("ICPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC/Passport Number.
        /// </summary>
        public static string ICPassportNumber {
            get {
                return ResourceManager.GetString("ICPassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC/Passport Type.
        /// </summary>
        public static string ICPassportType {
            get {
                return ResourceManager.GetString("ICPassportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Details.
        /// </summary>
        public static string IdentityDetails {
            get {
                return ResourceManager.GetString("IdentityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP you entered is invalid. Please try again..
        /// </summary>
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Rate.
        /// </summary>
        public static string LiveRate {
            get {
                return ResourceManager.GetString("LiveRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the Pre Booking to skip the Queue.
        /// </summary>
        public static string MCLblTxt {
            get {
                return ResourceManager.GetString("MCLblTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Exchange.
        /// </summary>
        public static string MoneyExchange {
            get {
                return ResourceManager.GetString("MoneyExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange cash to MYR.
        /// </summary>
        public static string MoneyExchangeDesc {
            get {
                return ResourceManager.GetString("MoneyExchangeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Mx_Back {
            get {
                return ResourceManager.GetString("Mx_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert cash.
        /// </summary>
        public static string Mx_CashIn {
            get {
                return ResourceManager.GetString("Mx_CashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Mx_Complete {
            get {
                return ResourceManager.GetString("Mx_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this you?.
        /// </summary>
        public static string Mx_ConfirmIdentity {
            get {
                return ResourceManager.GetString("Mx_ConfirmIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Mx_Continue {
            get {
                return ResourceManager.GetString("Mx_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer details.
        /// </summary>
        public static string Mx_CustomerDetails {
            get {
                return ResourceManager.GetString("Mx_CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not ready.
        /// </summary>
        public static string Mx_DeviceNotReady {
            get {
                return ResourceManager.GetString("Mx_DeviceNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Mx_Dob {
            get {
                return ResourceManager.GetString("Mx_Dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Mx_Done {
            get {
                return ResourceManager.GetString("Mx_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face verification.
        /// </summary>
        public static string Mx_FaceVerify {
            get {
                return ResourceManager.GetString("Mx_FaceVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Mx_FullName {
            get {
                return ResourceManager.GetString("Mx_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted.
        /// </summary>
        public static string Mx_Inserted {
            get {
                return ResourceManager.GetString("Mx_Inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert notes one by one.
        /// </summary>
        public static string Mx_InsertNotes {
            get {
                return ResourceManager.GetString("Mx_InsertNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual entry.
        /// </summary>
        public static string Mx_ManualEntry {
            get {
                return ResourceManager.GetString("Mx_ManualEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Mx_Nationality {
            get {
                return ResourceManager.GetString("Mx_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Mx_Next {
            get {
                return ResourceManager.GetString("Mx_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not you.
        /// </summary>
        public static string Mx_NotYou {
            get {
                return ResourceManager.GetString("Mx_NotYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No.
        /// </summary>
        public static string Mx_PassportNo {
            get {
                return ResourceManager.GetString("Mx_PassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing….
        /// </summary>
        public static string Mx_Processing {
            get {
                return ResourceManager.GetString("Mx_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Mx_Rate {
            get {
                return ResourceManager.GetString("Mx_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading….
        /// </summary>
        public static string Mx_Reading {
            get {
                return ResourceManager.GetString("Mx_Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Mx_Receipt {
            get {
                return ResourceManager.GetString("Mx_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new.
        /// </summary>
        public static string Mx_RegisterNew {
            get {
                return ResourceManager.GetString("Mx_RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove passport.
        /// </summary>
        public static string Mx_RemovePassport {
            get {
                return ResourceManager.GetString("Mx_RemovePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan IC.
        /// </summary>
        public static string Mx_ScanIC {
            get {
                return ResourceManager.GetString("Mx_ScanIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan passport.
        /// </summary>
        public static string Mx_ScanPassport {
            get {
                return ResourceManager.GetString("Mx_ScanPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select currency.
        /// </summary>
        public static string Mx_SelectCurrency {
            get {
                return ResourceManager.GetString("Mx_SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Mx_Sex {
            get {
                return ResourceManager.GetString("Mx_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Mx_Target {
            get {
                return ResourceManager.GetString("Mx_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Exchange.
        /// </summary>
        public static string Mx_Title {
            get {
                return ResourceManager.GetString("Mx_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Mx_Welcome {
            get {
                return ResourceManager.GetString("Mx_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You give.
        /// </summary>
        public static string Mx_YouGive {
            get {
                return ResourceManager.GetString("Mx_YouGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive (MYR).
        /// </summary>
        public static string Mx_YouReceive {
            get {
                return ResourceManager.GetString("Mx_YouReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No beneficiaries found.
        /// </summary>
        public static string NoBeneficiariesFound {
            get {
                return ResourceManager.GetString("NoBeneficiariesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, I&apos;ll Select.
        /// </summary>
        public static string OKIllSelect {
            get {
                return ResourceManager.GetString("OKIllSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP has expired. Please request a new one..
        /// </summary>
        public static string OTPExpired {
            get {
                return ResourceManager.GetString("OTPExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 6-digit One-Time Password has been sent to your registered mobile number..
        /// </summary>
        public static string OTPSentInfo {
            get {
                return ResourceManager.GetString("OTPSentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Verification.
        /// </summary>
        public static string OTPVerification {
            get {
                return ResourceManager.GetString("OTPVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay at Counter.
        /// </summary>
        public static string PayAtCounter {
            get {
                return ResourceManager.GetString("PayAtCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with Card.
        /// </summary>
        public static string PayWithCard {
            get {
                return ResourceManager.GetString("PayWithCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Information.
        /// </summary>
        public static string ProfileInformation {
            get {
                return ResourceManager.GetString("ProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your identification and contact details.
        /// </summary>
        public static string ProvideIDContact {
            get {
                return ResourceManager.GetString("ProvideIDContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Remittance.
        /// </summary>
        public static string PurposeOfRemittance {
            get {
                return ResourceManager.GetString("PurposeOfRemittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Exchange.
        /// </summary>
        public static string QueueXchange {
            get {
                return ResourceManager.GetString("QueueXchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Rates.
        /// </summary>
        public static string RatesToday {
            get {
                return ResourceManager.GetString("RatesToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Remittance &amp; Money Exchange Rates.
        /// </summary>
        public static string RatesTxt {
            get {
                return ResourceManager.GetString("RatesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Beneficiaries.
        /// </summary>
        public static string RecentBeneficiaries {
            get {
                return ResourceManager.GetString("RecentBeneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remittance Details.
        /// </summary>
        public static string RemittanceDetails {
            get {
                return ResourceManager.GetString("RemittanceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend OTP.
        /// </summary>
        public static string ResendOTP {
            get {
                return ResourceManager.GetString("ResendOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review all details carefully before proceeding to payment.
        /// </summary>
        public static string ReviewCarefully {
            get {
                return ResourceManager.GetString("ReviewCarefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the details of your transfer.
        /// </summary>
        public static string ReviewDetails {
            get {
                return ResourceManager.GetString("ReviewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Transaction.
        /// </summary>
        public static string ReviewTransaction {
            get {
                return ResourceManager.GetString("ReviewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and complete your transfer information.
        /// </summary>
        public static string ReviewTransfer {
            get {
                return ResourceManager.GetString("ReviewTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Sender Details.
        /// </summary>
        public static string SaveSenderDetails {
            get {
                return ResourceManager.GetString("SaveSenderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name or account number....
        /// </summary>
        public static string SearchByNameOrAccount {
            get {
                return ResourceManager.GetString("SearchByNameOrAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Transfer.
        /// </summary>
        public static string SecureTransfer {
            get {
                return ResourceManager.GetString("SecureTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a country first.
        /// </summary>
        public static string SelectCountryFirst {
            get {
                return ResourceManager.GetString("SelectCountryFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Destination.
        /// </summary>
        public static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Existing Beneficiary.
        /// </summary>
        public static string SelectExistingBeneficiary {
            get {
                return ResourceManager.GetString("SelectExistingBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from your previously saved beneficiary profiles.
        /// </summary>
        public static string SelectFromPrevious {
            get {
                return ResourceManager.GetString("SelectFromPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a service to continue.
        /// </summary>
        public static string SelectMenu {
            get {
                return ResourceManager.GetString("SelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing beneficiary or create a new profile.
        /// </summary>
        public static string SelectOrCreateBeneficiary {
            get {
                return ResourceManager.GetString("SelectOrCreateBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payment Method.
        /// </summary>
        public static string SelectPaymentMethod {
            get {
                return ResourceManager.GetString("SelectPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Amount.
        /// </summary>
        public static string SendAmount {
            get {
                return ResourceManager.GetString("SendAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Details.
        /// </summary>
        public static string SenderDetails {
            get {
                return ResourceManager.GetString("SenderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Photo (Optional).
        /// </summary>
        public static string SenderPhoto {
            get {
                return ResourceManager.GetString("SenderPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Money To.
        /// </summary>
        public static string SendingMoneyTo {
            get {
                return ResourceManager.GetString("SendingMoneyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Money.
        /// </summary>
        public static string SendMoney {
            get {
                return ResourceManager.GetString("SendMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Fee.
        /// </summary>
        public static string ServiceFee {
            get {
                return ResourceManager.GetString("ServiceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send money abroad quickly and securely.
        /// </summary>
        public static string SMLblTxt {
            get {
                return ResourceManager.GetString("SMLblTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source of Funds.
        /// </summary>
        public static string SourceOfFunds {
            get {
                return ResourceManager.GetString("SourceOfFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Transaction.
        /// </summary>
        public static string StartNewTransaction {
            get {
                return ResourceManager.GetString("StartNewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartTxt {
            get {
                return ResourceManager.GetString("StartTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province.
        /// </summary>
        public static string StateProvince {
            get {
                return ResourceManager.GetString("StateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL AMOUNT.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify OTP.
        /// </summary>
        public static string VerifyOTP {
            get {
                return ResourceManager.GetString("VerifyOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW RATES.
        /// </summary>
        public static string ViewRateTxt {
            get {
                return ResourceManager.GetString("ViewRateTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Us.
        /// </summary>
        public static string VisitOmni {
            get {
                return ResourceManager.GetString("VisitOmni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields Missing.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within minutes.
        /// </summary>
        public static string WithinMinutes {
            get {
                return ResourceManager.GetString("WithinMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Send.
        /// </summary>
        public static string YouSend {
            get {
                return ResourceManager.GetString("YouSend", resourceCulture);
            }
        }
    }
}
